version: '3'

services:
  runner:
    build: .
    environment:
      - ORGANIZATION=<ORGANIZATION-NAME>
      - REPO=<REPOSITORY-NAME>
      - RUNNER_TOKEN=<RUNNER-TOKEN> # Settings > Actions > Add Runner > Configure > find "--token AB...."

